### Dataset Link - [Sales_dataset](https://drive.google.com/file/d/1ovgq8DrPQsOcqTzc_mse0XJxtU5Wo5F-/view)

### Load the dataset

In [2]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Advanced_pandas_sales_dataset.csv')

Saving Advanced_pandas_sales_dataset.csv to Advanced_pandas_sales_dataset (1).csv

### Q1. Perform the following exploratory steps:
- Display the first 10 rows
- Display the dataset structure using info()
- Find the number of rows and columns
- Identify the data types of each column

In [3]:
# Solution Q1 --> part 1
df.head(10)

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

In [4]:
# Solution Q1 --> part 2
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

In [5]:
# Solution Q1 --> part 3
df.shape

(230, 11)

In [6]:
# Solution Q1 --> part 4
df.dtypes

Order_ID        int64
Order_Date     object
Customer       object
City           object
Region         object
Product        object
Category       object
Sales           int64
Quantity        int64
Discount      float64
Profit        float64
dtype: object

### Q2. Filter the dataset to display:
1. Orders where Sales > 3500
2. Orders where Region = "East" and Sales > 2500

Explain what insights you observe.

In [9]:
# Solution Q2 --> part 1
df[df['Sales'] > 3500]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
10,1011,2024-06-30,Neha,Delhi,South,Printer,Office,5977,6,0.00,1578.32
...,...,...,...,...,...,...,...,...,...,...,...
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [10]:
# Solution Q2 --> part 2
df[(df["Region"] == "East") & (df["Sales"] > 2500)]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
13,1014,2024-03-18,Anita,Bangalore,East,Mouse,Accessories,3616,4,0.05,463.93
21,1022,2024-01-14,Nitin,Chennai,East,Monitor,Electronics,4827,6,0.05,912.34
27,1028,2024-07-21,Dev,Kolkata,East,Tablet,Electronics,4054,6,0.00,1013.83
33,1034,2024-12-15,Nitin,Ahmedabad,East,Tablet,Electronics,4378,2,0.20,-104.30
34,1035,2024-02-20,Nitin,Ahmedabad,East,Laptop,Electronics,2535,4,0.10,188.15
41,1042,2024-07-15,Rohan,Chennai,East,Laptop,Electronics,3268,8,0.15,295.15
43,1044,2024-09-20,Kavya,Hyderabad,East,Printer,Office,2618,7,0.05,454.64
52,1053,2024-05-24,Anita,Chennai,East,Phone,Electronics,5949,7,0.20,220.44
55,1056,2024-01-03,Sneha,Chennai,East,Headphones,Accessories,2784,4,0.05,474.60
58,1059,2024-12-30,Anita,Delhi,East,Tablet,Electronics,4790,1,0.20,238.53
60,1061,2024-02-05,Nitin,Delhi,East,Monitor,Electronics,4508,5,0.00,972.35
70,1071,2024-05-28,Vikas,Hyderabad,East,Mouse,Accessories,3762,2,0.05,719.68
71,1072,2024-05-20,Rahul,Chennai,East,Printer,Office,3696,2,0.10,600.75
73,1074,2024-10-10,Sara,Bangalore,East,Mouse,Accessories,4004,1,0.15,445.81
74,1075,2024-11-25,Pooja,Ahmedabad,East,Laptop,Electronics,3865,8,0.20,174.96
76,1077,2024-03-02,Neha,Pune,East,Monitor,Electronics,2964,8,0.20,109.33
81,1082,2024-08-16,Isha,Chennai,East,Phone,Electronics,2720,4,0.15,163.13
87,1088,2024-07-29,Pooja,Mumbai,East,Headphones,Accessories,4811,4,0.20,-25.47
92,1093,2024-01-13,Karan,Kolkata,East,Laptop,Electronics,5372,3,0.15,136.64
96,1097,2024-06-07,Isha,Delhi,East,Phone,Electronics,5096,4,0.15,283.66
98,1099,2024-07-26,Rahul,Kolkata,East,Laptop,Electronics,5674,7,0.05,1141.51
108,1109,2024-10-23,Raj,Hyderabad,East,Tablet,Electronics,2509,4,0.05,371.67
109,1110,2024-11-28,Priya,Ahmedabad,East,Printer,Office,2561,4,0.20,57.96
112,1113,2024-11-01,Meera,Bangalore,East,Tablet,Electronics,4179,5,0.00,754.64
113,1114,2024-05-10,Rahul,Bangalore,East,Mouse,Accessories,3285,3,0.00,625.46
116,1117,2024-12-07,Pooja,Kolkata,East,Tablet,Electronics,3758,5,0.15,446.54
128,1129,2024-06-09,Nitin,Delhi,East,Laptop,Electronics,5713,3,0.00,1498.02
139,1140,2024-05-04,Karan,Ahmedabad,East,Monitor,Electronics,3500,8,0.05,467.16
141,1142,2024-01-01,Rahul,Mumbai,East,Headphones,Accessories,5430,8,0.05,741.25
146,1147,2024-05-31,Raj,Delhi,East,Keyboard,Accessories,5709,7,0.20,383.58
152,1153,2024-02-27,Rahul,Mumbai,East,Phone,Electronics,3644,2,0.05,512.25
156,1157,2024-05-27,Neha,Kolkata,East,Laptop,Electronics,4906,4,0.00,1115.89
171,1172,2024-09-22,Neha,Hyderabad,East,Headphones,Accessories,4228,1,0.20,236.15
179,1180,2024-12-13,Neha,Ahmedabad,East,Monitor,Electronics,2690,7,0.10,452.70
182,1183,2024-12-01,Pooja,Chennai,East,Laptop,Electronics,5884,1,0.05,1266.10
185,1186,2024-03-12,Kavya,Ahmedabad,East,Phone,Electronics,5047,2,0.10,564.78
187,1188,2024-07-10,Isha,Kolkata,East,Mouse,Accessories,4333,8,0.10,667.53
193,1194,2024-07-23,Pooja,Delhi,East,Laptop,Electronics,3767,7,0.20,103.23
197,1198,2024-10-16,Rahul,Ahmedabad,East,Tablet,Electronics,3955,1,0.10,284.92
202,1203,2024-05-10,Rahul,Mumbai,East,Phone,Electronics,2901,8,0.15,252.25
207,1208,2024-04-29,Dev,Chennai,East,Monitor,Electronics,3585,7,0.15,287.44
216,1217,2024-08-16,Karan,Chennai,East,Monitor,Electronics,2643,5,0.15,78.53
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76

### Solution - Explaination/Insights

- The first filter identifies orders with sales greater than 3500, which represents the higher-value orders in the dataset.
- The second filter identifies high-value orders specifically from the East region. This helps determine whether the East region contributes significantly to high-sales transactions.

### Q3. Identify the top 5 customers based on the total sales. Hint: Use GroupBy with aggregation.

In [11]:
# Solution
top_customers = (
    df.groupby("Customer")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

display(top_customers)

Customer
Nitin    59820
Raj      58416
Rahul    52291
Dev      48500
Isha     46818
Name: Sales, dtype: int64

### Q4. Calculate the total sales generated by each region. Then identify: which region generated the highest revenue?

In [14]:
# Solution

regional_sales = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

display(regional_sales)

highest_revenue_region = regional_sales.idxmax()

display(highest_revenue_region)

Region
East     232675
South    183108
West     170227
North    158210
Name: Sales, dtype: int64

'East'

### Q5. Product Performance Analysis
- Calculate the total quantity sold for each product.
- Which product appears to be the most popular?

In [15]:
# Solution Q5 --> part 1
product_quantity = df.groupby("Product")["Quantity"].sum().sort_values(ascending=False)

display(product_quantity)

Product
Monitor       156
Phone         151
Tablet        150
Laptop        140
Mouse         122
Headphones    115
Keyboard      110
Printer       108
Name: Quantity, dtype: int64

In [16]:
# Solution Q5 --> part 2
most_popular_product = product_quantity.idxmax()
highest_quantity = product_quantity.max()

most_popular_product = pd.Series([most_popular_product, highest_quantity], index=["Product", "Quantity"])

display(most_popular_product)

Product     Monitor
Quantity        156
dtype: object

### Q6. Multi-Level Grouping
- Group the dataset by: Region and category
- Calculate the total sales for each combination
- What insights can you derive from this analysis?

In [21]:
# Solution Q6 --> part 1
region_category_sales = df.groupby(["Region", "Category"])["Sales"].sum().reset_index()

display(region_category_sales)

   Region     Category   Sales
0    East  Accessories   57646
1    East  Electronics  160907
2    East       Office   14122
3   North  Accessories   62052
4   North  Electronics   70023
5   North       Office   26135
6   South  Accessories   80914
7   South  Electronics   86690
8   South       Office   15504
9    West  Accessories   64811
10   West  Electronics   84128
11   West       Office   21288

In [19]:
# Solution Q6 --> part 2
region_category_sales = df.groupby(["Region", "Category"])["Sales"].sum().reset_index().sort_values("Sales", ascending=False)

display(region_category_sales)

   Region     Category   Sales
1    East  Electronics  160907
7   South  Electronics   86690
10   West  Electronics   84128
6   South  Accessories   80914
4   North  Electronics   70023
9    West  Accessories   64811
3   North  Accessories   62052
0    East  Accessories   57646
5   North       Office   26135
11   West       Office   21288
8   South       Office   15504
2    East       Office   14122

###  Solution Q6 --> part 3 --> Explaination/Insights

- This analysis allows us to compare both region and category simultaneously.
- East region performs particularly well for a particular category
- Electronics & Accessories perform consistently across multiple regions
- Many region-category combinations contribute significantly more revenue than others.

### Q7. Create a pivot table showing:
- Rows --> Region
- Columns --> Product
- Values --> Total Sales

Which region sells the most laptops?

In [22]:
# Solution
pivot_table = pd.pivot_table(
    df,
    index = "Region",
    columns = "Product",
    values = "Sales",
    aggfunc = "sum",
    fill_value = 0
)

display(pivot_table)

laptop_sales = pivot_table["Laptop"]

region_most_Laptops = laptop_sales.idxmax()
highest_laptop_sales = laptop_sales.max()

region_most_Laptops = pd.Series([region_most_Laptops, highest_laptop_sales], index=["Region", "Sales"])

display(region_most_Laptops)

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274

Region     East
Sales     55568
dtype: object

### Q8. Profitability Analysis
- Calculate the average profit for each product category.
- Which category is most profitable?

In [23]:
# Solution

category_profit = df.groupby("Category")["Profit"].mean().sort_values(ascending=False)

display(category_profit)

most_profitable_category = category_profit.idxmax()
highest_profit = category_profit.max()

most_profitable_category = pd.Series([most_profitable_category, highest_profit], index=["Category", "Profit"])

display(most_profitable_category)

Category
Office         471.938462
Accessories    410.603086
Electronics    396.462114
Name: Profit, dtype: float64

Category        Office
Profit      471.938462
dtype: object

### Q9. Analyze the relationship between discount and profit. Tasks:
- Calculate the average profit for each discount level
- Identify whether higher discounts lead to lower profit

In [24]:
# Solution Q9 --> part 1
discount_profit = df.groupby("Discount")["Profit"].mean().sort_index()

display(discount_profit)

Discount
0.00    751.210588
0.05    531.368039
0.10    346.460513
0.15    237.191400
0.20     90.026923
Name: Profit, dtype: float64

In [28]:
# Solution Q9 --> part 2

correlation = df["Discount"].corr(df["Profit"])

print("Correlation is: ",correlation)
print("\nInterpretation is: ")

if correlation < 0:
  print("As discount increases, profit decreases.")
elif correlation > 0:
  print("As discount increases, profit increases.")
else:
  print("There is no correlation between discount and profit.")

Correlation is:  -0.6637047529855844

Interpretation is:
As discount increases, profit decreases.

### Q10. Perform the following workflow:
1. Filter the dataset where Sales > 3000
2. Group data by Region and Product
3. Calculate total Sales
4. Reshape the result into a pivot table

Explain the business insights obtained from this analysis.

In [29]:
# Solution

filtered_df = df[df["Sales"] > 3000]
print("The dataset with Sales > 3000 is: ")
display(filtered_df)

grouped_df = filtered_df.groupby(["Region", "Product"])["Sales"].sum().reset_index()
print("\nThe grouped dataset is: ")
display(grouped_df)

final_pivot = pd.pivot_table(
    grouped_df,
    index = "Region",
    columns = "Product",
    values = "Sales",
    aggfunc = "sum",
    fill_value = 0
)
print("\nThe final pivot table is: ")
display(final_pivot)

# Interpretation
print("\nInterpretation is: ")

print("\nThe analysis focuses only on orders with sales greater than 3000. The pivot table makes it easy to compare high-value sales across different regions and products. It helps identify which products generate the highest sales in each region and which regions have stronger performance for particular products. This information can be used to identify high-performing products, strong regional markets, and potential areas for sales improvement.")

The dataset with Sales > 3000 is:

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
...,...,...,...,...,...,...,...,...,...,...,...
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

The grouped dataset is:

   Region     Product  Sales
0    East  Headphones  14469
1    East    Keyboard   9642
2    East      Laptop  44096
3    East     Monitor  16420
4    East       Mouse  19000
5    East       Phone  29500
6    East     Printer   3696
7    East      Tablet  29229
8   North  Headphones   5326
9   North    Keyboard  15653
10  North      Laptop   4540
11  North     Monitor   5087
12  North       Mouse  22209
13  North       Phone  24670
14  North     Printer  17185
15  North      Tablet   3392
16  South  Headphones  10026
17  South    Keyboard  19249
18  South      Laptop  17950
19  South     Monitor  14921
20  South       Mouse  26928
21  South       Phone  18218
22  South     Printer  14143
23  South      Tablet  19613
24   West  Headphones  13898
25   West    Keyboard  33380
26   West      Laptop   5922
27   West     Monitor  14354
28   West       Mouse   3511
29   West       Phone  15653
30   West     Printer  12648
31   West      Tablet  17185

The final pivot table is:

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          14469      9642   44096    16420  19000  29500     3696   29229
North          5326     15653    4540     5087  22209  24670    17185    3392
South         10026     19249   17950    14921  26928  18218    14143   19613
West          13898     33380    5922    14354   3511  15653    12648   17185

Interpretation is:

The analysis focuses only on orders with sales greater than 3000. The pivot table makes it easy to compare high-value sales across different regions and products. It helps identify which products generate the highest sales in each region and which regions have stronger performance for particular products. This information can be used to identify high-performing products, strong regional markets, and potential areas for sales improvement.